# .github/workflows/build-macos-app.yml

name: Build macOS App

on:
  workflow_dispatch:   # 允许手动触发
  push:
    tags:
      - "v*"          # 当你打 tag 的时候也会触发

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        # 使用最新的 v4 版本
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          architecture: 'arm64'

      # --- 修改的核心部分 ---
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install py2app dmgbuild
          pip install -r requirements-macos.txt


      - name: Build .app
        run: |
          python setup.py py2app

      - name: Create DMG
        run: |
          dmgbuild -s dmg_settings.py "Arkham Card Maker" "dist/Arkham-Card-Maker.dmg"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Arkham-Card-Maker
          path: |
            dist/*.app
            dist/*.dmg
